describe("Add Product Test Scenario", ()=>{
    it('user success add product to kasir Aja', ()=>{
        cy.visit(Cypress.env('baseUrl'))
        cy.get('#email').type(Cypress.env('email'))
        cy.get('#password').type(Cypress.env('password'))
        cy.get('#root > div > div > div > div.css-1w7v3tn > div > button').click()
        cy.get('[href="/products"] > .css-ewi1jp > .css-1xhj18k > .css-1mqa38q').click()
        cy.get('.css-1piskbq').click()
        cy.get('#nama').type('Bengbeng')
        cy.get('#deskripsi').type('Bengbeng')
        cy.get('[id$="beli"]').type('3000')
        cy.get('[id$="jual"]').type('5000')
        cy.get('#stok').type('50')
        cy.get('.chakra-input__right-addon').click()
        cy.get(':nth-child(3) > .css-u3dlpe').click()
        cy.contains('simpan').click()
        cy.contains('item ditambahkan', { timeout: 10000 })
    }),
    it('user unsuccess add product to kasir Aja because name is empty', ()=>{
        cy.visit(Cypress.env('baseUrl'))
        cy.get('#email').type(Cypress.env('email'))
        cy.get('#password').type(Cypress.env('password'))
        cy.get('#root > div > div > div > div.css-1w7v3tn > div > button').click()
        cy.get('[href="/products"] > .css-ewi1jp > .css-1xhj18k > .css-1mqa38q', { timeout: 10000 }).click()
        cy.get('.css-1piskbq').click()
        cy.contains('simpan').click()
        cy.contains('"name" is not allowed to be empty')
    }),
    it('user unsuccess add product to kasir Aja because the purchase price is greater than the selling price', ()=>{
        cy.visit(Cypress.env('baseUrl'))
        cy.get('#email').type(Cypress.env('email'))
        cy.get('#password').type(Cypress.env('password'))
        cy.get('#root > div > div > div > div.css-1w7v3tn > div > button').click()
        cy.get('[href="/products"] > .css-ewi1jp > .css-1xhj18k > .css-1mqa38q', { timeout: 10000 }).click()
        cy.get('.css-1piskbq').click()
        cy.get('#nama').type('Bengbeng')
        cy.get('#deskripsi').type('Bengbeng')
        cy.get('[id$="beli"]').type('5000')
        cy.get('[id$="jual"]').type('3000')
        cy.get('#stok').type('50')
        cy.get('.chakra-input__right-addon').click()
        cy.get(':nth-child(3) > .css-u3dlpe').click()
        cy.contains('simpan').click()
        cy.contains('"price" must be greater than ref:cost')
    }),
    it('user unsuccess add product to kasir Aja because no choosing category', ()=>{
        cy.visit(Cypress.env('baseUrl'))
        cy.get('#email').type(Cypress.env('email'))
        cy.get('#password').type(Cypress.env('password'))
        cy.get('#root > div > div > div > div.css-1w7v3tn > div > button').click()
        cy.get('[href="/products"] > .css-ewi1jp > .css-1xhj18k > .css-1mqa38q', { timeout: 10000 }).click()
        cy.get('.css-1piskbq').click()
        cy.get('#nama').type('Bengbeng')
        cy.get('#deskripsi').type('Bengbeng')
        cy.get('[id$="beli"]').type('3000')
        cy.get('[id$="jual"]').type('5000')
        cy.get('#stok').type('50')
        cy.contains('simpan').click()
        cy.contains('"category_id" is required')
    })
})